/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/builder.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/builder -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/builder
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/comptime.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/comptime -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/comptime
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/comptime_stress.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/comptime_stress -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/comptime_stress
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/container_api.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/container_api -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/container_api
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/freestanding_gate.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/freestanding_gate -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/freestanding_gate
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/fuzz_parse.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/fuzz_parse -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/fuzz_parse
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/insitu.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/insitu -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/insitu
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/minify.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/minify -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/minify
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/number.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/number -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/number
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/ondemand.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/ondemand -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/ondemand
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/parse.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/parse -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/parse
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/stage1.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/stage1 -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/stage1
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/string.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/string -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/string
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/utf8.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/utf8 -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/utf8
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/write.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/write -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/write
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/text_source.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/text_source -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/text_source
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/fp.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/fp -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/fp
/usr/gcc-linaro/bin/arm-none-linux-gnueabihf-c++ -std=c++26 -Ofast -march=armv7-a -mfpu=neon -mfloat-abi=hard -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -static -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/oneshot.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/arm/oneshot -static-libgcc -static-libstdc++
/usr/bin/qemu-arm-static -L /usr/gcc-linaro/arm-none-linux-gnueabihf/libc bin/arm/oneshot
