/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/builder.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/builder
bin/builder
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/comptime.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/comptime
bin/comptime
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/comptime_stress.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/comptime_stress
bin/comptime_stress
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/container_api.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/container_api
bin/container_api
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/freestanding_gate.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/freestanding_gate
bin/freestanding_gate
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/fuzz_parse.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/fuzz_parse
bin/fuzz_parse
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/insitu.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/insitu
bin/insitu
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/minify.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/minify
bin/minify
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/number.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/number
bin/number
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/ondemand.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/ondemand
bin/ondemand
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/parse.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/parse
bin/parse
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/stage1.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/stage1
bin/stage1
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/string.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/string
bin/string
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/utf8.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/utf8
bin/utf8
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/write.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/write
bin/write
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/text_source.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/text_source
bin/text_source
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/fp.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/fp
bin/fp
/usr/bin/g++ -std=c++26 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fstack-protector-all -fstack-clash-protection -fstrict-overflow -fext-numeric-literals -flto=8 -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/oneshot.cpp -lpthread -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -L./libs/ -o bin/oneshot
bin/oneshot
